"""Compatibility import surface for similarity helpers.

The implementation now lives in smaller modules grouped by responsibility, but
this shim keeps the original notebook-facing import path stable.
"""

from src.similarity_core import (
    _effective_max_length,
    _get_encoder,
    _image_path_to_data_uri,
    build_tokenization_preview,
    build_variant_preview_sequences,
    collect_preview_sequences,
    compare_sequence_pair,
    compare_sequence_pairs,
    embed_sequences,
    load_similarity_artifacts,
    plot_similarity_heatmap,
    resolve_device,
    run_similarity_analysis,
    save_similarity_outputs,
    similarity_matrix,
    similarity_matrix_dataframe,
    tokenize_sequence,
    validate_similarity_inputs,
)
from src.similarity_scaleup import (
    attach_pca_to_specific_html,
    _build_matrix_labels,
    _clean_similarity_dataframe,
    _collect_scaleup_html_sequences,
    _format_summary_table_rows,
    _summarize_similarity_values,
    attach_pca_to_scaleup_index_html,
    build_focus_cloud_membership,
    build_public_export_dir,
    build_public_report_subdir,
    build_all_vs_all_artifacts,
    build_embedding_lookup_for_dataframe,
    build_similarity_distribution_summary,
    build_threshold_cloud_table,
    compare_queries_to_corpus,
    export_public_scaleup_html,
    plot_similarity_distribution_histogram,
    render_scaleup_index_html,
    render_specific_vs_all_html,
    run_scaleup_similarity_analysis,
    save_scaleup_pca_outputs,
    save_scaleup_similarity_outputs,
    validate_scaleup_similarity_inputs,
)
from src.similarity_model_comparison import export_public_similarity_model_comparison_html
from src.similarity_pooling_comparison import (
    MATCH_KEYS,
    POOLING_ORDER,
    SUMMARY_COLUMNS as POOLING_SUMMARY_COLUMNS,
    build_matched_pooling_score_table,
    build_notebook8_output_run_label,
    build_pooling_metric_comparison,
    build_pooling_pairwise_correlations,
    build_pooling_query_inspection_table,
    build_pooling_run_specs,
    build_pooling_similarity_summary,
    build_pooling_similarity_summary_by_query,
    build_pooling_three_way_top_k_overlap_summary,
    build_pooling_top_k_overlap,
    build_pooling_top_k_overlap_summary,
    export_public_pooling_metric_comparison_html,
    load_matched_pooling_outputs,
    plot_pooling_metric_matrix,
    render_pooling_metric_comparison_html_report,
)
from src.similarity_variants import (
    DEFAULT_VARIANT_MODEL_SUITE,
    VARIANT_SET_ORDER,
    build_variant_model_run_specs,
    _humanize_label,
    _normalize_variant_set_name,
    _sort_variant_results,
    _variant_set_heading,
    _variant_set_sort_key,
    build_anchor_similarity_matrices,
    build_variant_summary_tables,
    compare_anchor_variants,
    export_public_variant_html,
    plot_variant_similarity_histogram,
    render_anchor_similarity_html,
    render_variant_index_html,
    run_variant_similarity_analysis,
    run_variant_similarity_model_suite,
    save_variant_similarity_outputs,
    validate_variant_similarity_inputs,
)

__all__ = [name for name in globals() if not name.startswith('__')]
